---
name: FlowInsight
description: >
  A data analytics processing pipeline for IPFIX streams.
version: 0.0.1-rancher1
category: FlowInsight
maintainer: Richard Rothwell <richard.rothwell@aarnet.edu.au>
license: Apache2
projectURL: https://git.cdn.aarnet.edu.au/aarnet_network_analytics/flow_insight_rancher
